name: CI

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/*.md'

  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**/*.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: browser-actions/setup-chrome@latest
      - run: npm i
      - run: npm run test:headless

  build:
    name: Build
    needs: test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: npm run build
